##############################################################################
#                   Authelia configuration                                   #
##############################################################################

theme: grey

server:
  address: tcp://0.0.0.0:9091/
  buffers:
    read: 8192
    write: 8192

log:
  level: info
  ## Format the logs are written as: json, text.
  # format: json
  ## File path where the logs will be written. If not set logs are written to stdout.
  file_path: /config/authelia.log
  ## Whether to also log to stdout when a log_file_path is defined.
  keep_stdout: true

ntp:
  address: "time.cloudflare.com:123"
  version: 4
  max_desync: 3s
  disable_startup_check: false

regulation:
  max_retries: 5
  find_time: 2m
  ban_time: 10m

storage:
  encryption_key: SoMe1StRiNg2GoEs3In4HeRe
  # mysql:
  #   host: mariadb
  #   port: 3306
  #   database: autheliadb
  #   username: authelia
  #   password: PASSWORD
  local:
    path: /config/db.sqlite3

identity_validation:
  reset_password:
    jwt_lifespan: '5 minutes'
    jwt_algorithm: 'HS256'
    jwt_secret: 'SoMe1StRiNg2GoEs3In4HeRe'

default_redirection_url: https://auth.MYDOMAIN.COM

totp:
  disable: false
  issuer: MYDOAMIN.COM
  period: 30
  skew: 1

webauthn:
  disable: false
  display_name: Authelia
  attestation_conveyance_preference: indirect
  user_verification: preferred
  timeout: 60s

notifier:
  disable_startup_check: true
#  filesystem:
#    filename: /config/notification.txt
  smtp: #https://support.google.com/accounts/answer/185833?hl=en
    address: submissions://smtp.gmail.com:465
    timeout: 5s
    disable_require_tls: true
    disable_html_emails: false
    username: USERNAME@gmail.com
    password: PASSWORD
    sender: "My Authentication Service <noreply@auth.MYDOMAIN.com>"
    subject: "[2FA] {title}"
    startup_check_address: noreply@auth.MYDOMAIN.com

authentication_backend:
  password_reset.disable: false
  file:
    path: /config/users_database.yml
    password:
      algorithm: argon2id
      iterations: 1
      salt_length: 16
      parallelism: 8
      memory: 64

session:
  name: authelia
  secret: SoMe1StRiNg2GoEs3In4HeRe
  expiration: 3600 # 1 hour
  inactivity: 7200 # 2 hours
  remember_me: 1M # Setting this to -1 disables this feature entirely.
  same_site: lax
  cookies:
    - domain: MYDOAMAIN.com # Needs to be root domain
      authelia_url: https://auth.MYDOAMAIN.com
      default_redirection_url: https://www.MYDOAMAIN.com
  redis:
    host: redis
    port: 6379

access_control:
  networks:
    - name: docker
      networks:
         - 172.18.0.0/16
    - name: local
      networks:
         - 192.168.1.0/24
  rules:
    ## bypass rule
    - domain: 
        - "auth.MYDOAMAIN.com"
      policy: bypass


identity_providers:
  oidc:
    hmac_secret: thisiSaduMMY2String3u1SEDasasA2mP92es0E43crEtD84AT2Af8oRy3OU53AA
    jwks:
      - key_id: 'example'
        algorithm: 'RS256'
        use: 'sig'
        key: | # docker run -u 1036:100 -v /volume1/docker:/keys authelia/authelia:latest authelia crypto pair rsa generate --bits 4096 --directory /keys
          -----BEGIN RSA PRIVATE KEY-----
          private.pem CONTENTS TO BE INSERTED HERE
          -----END RSA PRIVATE KEY-----
    lifespans.access_token: 1h
    lifespans.authorize_code: 1m
    lifespans.id_token: 1h
    lifespans.refresh_token: 90m
    enable_client_debug_messages: false
    enforce_pkce: public_clients_only
    cors:
      endpoints:
        - authorization
        - token
        - revocation
        - introspection
      allowed_origins:
        - "*"
      allowed_origins_from_client_redirect_uris: false
    clients: 
      - client_id: cloudflare
        client_name: Cloudflare ZeroTrust
        client_secret: PUT THE (Digest) PASSPHRASE PREVIOUSLY GENERATED
        public: false
        authorization_policy: two_factor
        pre_configured_consent_duration: '365d'
        redirect_uris:
          - https://MYTEAM.cloudflareaccess.com/cdn-cgi/access/callback
        scopes:
          - openid
          - profile
          - email
        userinfo_signing_algorithm: none

