##############################################################################
#                   Authelia configuration                                   #
##############################################################################

theme: grey

server:
  host: 0.0.0.0
  port: 9091 # if you need this changed make sure it reflects also in the docker-compose.yml

log:
  level: info
  ## Format the logs are written as: json, text.
  # format: json
  ## File path where the logs will be written. If not set logs are written to stdout.
  file_path: /config/authelia.log
  ## Whether to also log to stdout when a log_file_path is defined.
  keep_stdout: true

ntp:
  address: "time.cloudflare.com:123"
  version: 4
  max_desync: 3s
  disable_startup_check: false

regulation:
  max_retries: 5
  find_time: 2m
  ban_time: 10m

storage:
  encryption_key: SoMe1StRiNg2GoEs3In4HeRe
  mysql:
    host: mariadb
    port: 3306
    database: autheliadb
    username: authelia
    password: PASSWORD
  # local:
  #   path: /config/db.sqlite3

jwt_secret: SoMe1StRiNg2GoEs3In4HeRe

default_redirection_url: https://auth.MYDOMAIN.COM

totp:
  disable: false
  issuer: MYDOAMIN.COM
  period: 30
  skew: 1

webauthn:
  disable: false
  display_name: Authelia
  attestation_conveyance_preference: indirect
  user_verification: preferred
  timeout: 60s

notifier:
  disable_startup_check: true
#  filesystem:
#    filename: /config/notification.txt

authentication_backend:
  password_reset.disable: false
  file:
    path: /config/users_database.yml
    password:
      algorithm: argon2id
      iterations: 1
      salt_length: 16
      parallelism: 8
      memory: 64

session:
  name: authelia
  secret: SoMe1StRiNg2GoEs3In4HeRe
  expiration: 3600 # 1 hour
  inactivity: 7200 # 2 hours
  domain: MYDOAMAIN>COM # Needs to be root domain
  same_site: lax
  redis:
    host: redis
    port: 6379

identity_providers:
  oidc:
    hmac_secret: szypeJnrhIQJ9Iczhyn9p1YFGxrmzZ1lX81erOP88koUiD78PF4Zc8vMw1VG24HS
    issuer_private_key: 
      -----BEGIN RSA PRIVATE KEY-----
      private.pem CONTENTS TO BE INSERTED HERE
      -----END RSA PRIVATE KEY-----
    access_token_lifespan: 1h
    authorize_code_lifespan: 1m
    id_token_lifespan: 1h
    refresh_token_lifespan: 90m
    enable_client_debug_messages: false
    enforce_pkce: public_clients_only
    cors:
      endpoints:
        - authorization
        - token
        - revocation
        - introspection
      allowed_origins:
        - "*"
      allowed_origins_from_client_redirect_uris: false
    clients:
      - id: CF-Access-Client-Id TOKEN
        description: Cloudflare ZeroTrust
        secret: CF-Access-Client-Secret TOKEN
        public: false
        authorization_policy: two_factor
        pre_configured_consent_duration: '365d'
        redirect_uris:
          - https://MYTEAM.cloudflareaccess.com/cdn-cgi/access/callback
        scopes:
          - openid
          - profile
          - email
        userinfo_signing_algorithm: none

